default:
  image: golang:1.24-alpine

stages:
  - lint
  - test
  - build

lint-code:
  stage: lint
  script:
    - echo "Linting code..."
    - go fmt $(go list ./...)
    - go vet $(go list ./...)

golangci-lint:
  stage: lint
  image: golangci/golangci-lint:v2.2-alpine
  script:
    - echo "Executando linter no código..."
    - golangci-lint run --verbose

run-tests:
  stage: test
  script:
    - echo "Rodando testes e gerando report..."
    - apk add --no-cache build-base gcc
    - go install gotest.tools/gotestsum@latest
    - CGO_ENABLED=1 gotestsum --junitfile report.xml --format testname
  artifacts:
    when: always
    reports:
      junit: report.xml

build-app:
  stage: build
  script:
    - echo "Compilando aplicação..."
    - go build main.go
