name: Deploy Infra (Koyeb via Terraform)

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

permissions:
  contents: read

concurrency:
  group: deploy-infra
  cancel-in-progress: false

env:
  TF_IN_AUTOMATION: true

jobs:
  terraform:
    runs-on: ubuntu-latest
    defaults:
      run:
        shell: bash
        working-directory: infra
    env:
      # KOYEB_TOKEN é lido pelo provider do Koyeb; configure como Secret no repositório
      KOYEB_TOKEN: ${{ secrets.KOYEB_TOKEN }}

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Validate KOYEB_TOKEN
        run: |
          if [ -z "${KOYEB_TOKEN}" ]; then
            echo "::error::Secret KOYEB_TOKEN não definido. Configure em Settings > Secrets and variables > Actions."
            exit 1
          fi

      - name: Setup Terraform
        uses: hashicorp/setup-terraform@v3
        with:
          terraform_wrapper: false

      - name: Terraform Init
        run: terraform init -upgrade

      - name: Terraform Validate
        run: terraform validate -no-color

      - name: Terraform Plan
        run: terraform plan -no-color

      - name: Terraform Apply (main only)
        if: github.event_name == 'push' && github.ref == 'refs/heads/main'
        run: terraform apply -auto-approve
