name: CI/CD - Saudações Aleatórias

on:
  push:
    branches:
      - '*'
  pull_request:
    branches:
      - main
  workflow_dispatch:

jobs:
  lint:
    name: Lint Code
    runs-on: ubuntu-latest
    steps:
    - name: Checkout Code
      uses: actions/checkout@v4

    - name: Set up Go
      uses: actions/setup-go@v5
    
    - name: Go Fmt & Vet
      run: |
        echo "Linting code..."
        go fmt $(go list ./...)
        go vet $(go list ./...)
  
  build:
    name: Build Code
    runs-on: ubuntu-latest
    steps:
    - name: Checkout Code
      uses: actions/checkout@v4

    - name: Set up Go
      uses: actions/setup-go@v5

    - name: Build app
      run: go build main.go


    
